APPLY_FIXES: all
DISABLE:
  - COPYPASTE
  - SPELL
DISABLE_LINTERS:
  - BASH_SHELLCHECK
  - PYTHON_FLAKE8
ACTION_ACTIONLINT_DISABLE_ERRORS: true
DEFAULT_BRANCH: master
REPORT_OUTPUT_FOLDER: .
ACTION_ACTIONLINT_ARGUMENTS: '-shellcheck='
