name: ci release

on: [pull_request]

jobs:
  self-release:
    uses: ./.github/workflows/release.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  upload_release:
    needs: [self-release]
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        id: wait-for-build
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          checkName: 'Run test-create (windows-latest, windows)'
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          timeoutSeconds: 1800

      - name: setFailed when not wait-for-build
        uses: actions/github-script@v6
        if: steps.wait-for-build.outputs.conclusion != 'success'
        with:
          script: |
            core.setFailed('conclusion is ${{ steps.wait-for-build.outputs.conclusion }}')

      - uses: actions/download-artifact@v3

      - uses: actions/checkout@v3
      - run: git push origin :refs/tags/latest-${{ github.base_ref }}

      - uses: ncipollo/release-action@v1
        with:
          tag: latest-${{ github.base_ref }}
          artifacts: ./AutoinstallCreator-*/*
          bodyFile: ./body/body.md
          allowUpdates: true
          removeArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
