name: ci release

on: [pull_request]

jobs:
  self-release:
    uses: ./.github/workflows/release.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  upload_release:
    needs: [self-release]
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: 'Run test-create (windows-latest, windows)'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - uses: actions/download-artifact@v3
        with:
          path: ./artifacts
      - uses: ncipollo/release-action@v1
        with:
          tag: latest-${{ github.ref_name }}
          artifacts: ./artifacts/*
          allowUpdates: true
          removeArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
