name: ci release

on: [pull_request]

jobs:
  self-release:
    uses: ./.github/workflows/release.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  upload_release:
    needs: [self-release]
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          checkName: 'Run test-create (windows-latest, windows)'
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v3
      - uses: ncipollo/release-action@v1
        if: steps.wait-for-build.outputs.conclusion == 'success'
        with:
          tag: latest-${{ github.ref_name }}
          artifacts: ./AutoinstallCreator-*/*
          allowUpdates: true
          removeArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
