name: ci release

on: [push]

jobs:
  self-release:
    uses: ./.github/workflows/release.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  upload_release:
    needs: [self-release]
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          checkName: 'Run test-create'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - uses: actions/download-artifact@v3
        with:
          path: ./artifacts
      - uses: ncipollo/release-action@v1
        with:
          tag: latest-${{ github.ref_name }}
          artifacts: ./artifacts/*
          allowUpdates: true
          removeArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
