name: ci release

on: [push]

jobs:
  self-release:
    uses: ./.github/workflows/release.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  upload_release:
    needs: [self-release]
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'Run test-create'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - uses: actions/download-artifact@v3
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ latest }}-${{ github.ref_name }}
          # TODO: download all artifacts
          # artifacts: ${{ inputs.artifacts }}
          allowUpdates: true
          removeArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
