on:
  workflow_call:
    inputs:
      workflow:
        description: tool name
        required: true
        type: string
      tool_version:
        description: tool version
        required: true
        type: string
    secrets:
      token:
        description: secrets.GITHUB_TOKEN
        required: true
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: 'ubuntu'

          - os: windows-latest
            artifact: 'windows'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3

      - if: matrix.artifact == 'ubuntu'
        run: ./_AutoinstallCreator/release.sh
        id: create_artifact

      - if: matrix.artifact == 'windows'
        run: ./.tools/busybox.exe sh ./_AutoinstallCreator/release.sh
        id: create_artifact

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.create_artifact.outputs.artifact_version }}-${{ matrix.artifact }}
          path: ${{ steps.create_artifact.outputs.artifact_path }}
