on:
  workflow_call:
    inputs:
      workflow:
        description: tool name
        required: true
        type: string
      tool_version:
        description: tool version
        required: true
        type: string
      prepare_body:
        description: scripts for prepare body.md
        required: true
        type: string
      artifacts:
        description: list of artifacts
        required: true
        type: string
    secrets:
      token:
        description: secrets.GITHUB_TOKEN
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3

      - run: ./_AutoinstallCreator/release.sh
        id: create_artifact

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.workflow }}-${{ inputs.tool_version }}
          bodyFile: './body.md'
          artifacts: ${{ steps.create_artifact.outputs.artifact_path }}
          allowUpdates: true
          removeArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}

