on:
  workflow_call:
    inputs:
      workflow:
        description: tool name
        required: true
        type: string
      tool_version:
        description: tool version
        required: true
        type: string
    secrets:
      token:
        description: secrets.GITHUB_TOKEN
        required: true

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: 'ubuntu'
            command: './_AutoinstallCreator/release.sh'

          - os: windows-latest
            artifact: 'windows'
            command: './.tools/busybox.exe sh ./_AutoinstallCreator/release.sh'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: ${{ matrix.command }}
        id: create_artifact

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.create_artifact.outputs.artifact_version }}-${{ matrix.artifact }}
          path: ${{ steps.create_artifact.outputs.artifact_path }}

  upload_release:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
      uses: lewagon/wait-on-check-action@v1.0.0
      with:
        ref: ${{ github.ref }}
        check-name: 'test-create'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10

