name: test-run windows

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: vc_runtime check
        shell: cmd
        run: |
          call .tests/test-run.bat vc_redist checkinstall
          call .tests/test-run.bat _7z checkinstall
          call .tests/test-run.bat _7z checkinstall 1

      - name: Internal test-run
        shell: cmd
        run: call .tests/test-run.bat _ create

      - name: Internal test-run mingw64
        shell: cmd
        run: call .tests/test-run.mingw64.bat _ create

      - name: External test-run
        shell: cmd
        run: call .tests/test-run.bat ! _ create

