name: test-run vagrant

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest
    env:
      VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1

    steps:
      - name: vagrant init
        run: |
          VBoxManage -version
          vagrant --version
          vagrant init devopsgroup-io/windows_server-2012r2-standard-amd64-nocm

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Run vagrant up
        run: vagrant up

      - name: ssh into box after boot
        run: vagrant ssh -c "echo 'hello world!'"
