name: test-run vagrant

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest
    env:
      VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1

    steps:
      - name: Update packages
        run: |
          brew uninstall --cask vagrant
          brew install --cask https://raw.githubusercontent.com/Homebrew/homebrew-cask/7f340b97d60907da225e9f5c10e81f9285ef2edb/Casks/vagrant.rb
          brew uninstall --cask virtualbox
          brew install --cask https://raw.githubusercontent.com/danielmenezesbr/homebrew-cask/virtualbox-6024/Casks/virtualbox.rb

      - name: Show packages version
        run: |
          VBoxManage --version
          vagrant up --version
      
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.vagrant.d/boxes/cdaf-VAGRANTSLASH-WindowsServerDC
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}


      - name: vagrant
        run: |
          vagrant plugin install vagrant-vbguest
          vagrant up dc
          vagrant powershell dc -c 'systeminfo'
