name: test-run vagrant-server-core

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest
    env:
      VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - run: vagrant up core

      - name: Vagrant internal test-run core
        run: |
          vagrant winrm core --shell cmd --command 'call set CI=true && C:\vagrant\.tests\test-run.bat _ create'

      - run: vagrant up win8.1

      - name: Vagrant internal test-run win8.1
        run: |
          vagrant winrm win8.1 --shell cmd --command 'call set CI=true && C:\vagrant\.tests\test-run.bat _ create'
