name: test-run linux

on: [pull_request]

jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Internal test-run
        run: .tests/test-run.sh _ create

  container:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Internal test-run
        run: |
         apk add --no-cache bash grep
         .tests/test-run.sh _ create

