name: test-run linux

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Internal test-run
        run: .tests/test-run.sh _ create

