name: test-run windows

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Internal test-run
        shell: cmd
        run: .tests/test-run.bat _ create
      - name: Internal test-run mingw64
        shell: cmd
        run: .tests/test-run.mingw64.bat _ create

