name: test-run vagrant-server-core

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest
    env:
      VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
    steps:
      - uses: actions/checkout@v2

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - run: vagrant up core

      - name: Vagrant internal test-run
        run: |
          vagrant winrm core --shell cmd --command 'call set CI=true && C:\vagrant\.tests\test-run.bat _ create'
