name: test-run linux

on: [push, pull_request]

jobs:
  ubuntu-host:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: sudo apt-get --assume-yes install pcre2-utils

      - name: test-run
        run: .tests/ci-test-run.sh

  alpine-docker:
    runs-on: ubuntu-latest
    container: alpine:3.15.0
    steps:
      - uses: actions/checkout@v2

      - name: Internal test-run
        run: |
          apk add --no-cache bash pcre2-tools
          .tests/ci-test-run.sh
